- .analysis_options
- lib/aes.dart
- lib/uuid.dart
- lib/uuid_util.dart
- pubspec.yaml
> Make dart-uuid strong-mode clean.

- lib/uuid.dart
The timestamp calculation was not working correctly. The ~/ was messing it up.
In the end, when I retrieved the timestamp from the TImeUUID, it was not the same that originated it.
I changed it to a floor and it is working correctly.
The code below prints the incorrect date retrieved from the uuid:
```
timestampFromTimeUuid(String uuid) {
var uuid_arr = uuid.split( '-' ),
time_str = [
uuid_arr[ 2 ].substring( 1 ),
uuid_arr[ 1 ],
uuid_arr[ 0 ]
].join( '' );
return int.parse( time_str, radix: 16 );
}
dateFromTimeUuid(String uuid) {
var int_time = timestampFromTimeUuid( uuid ) - 122192928000000000,
int_millisec = ( int_time / 10000 ).floor();
return DateTime.fromMillisecondsSinceEpoch( int_millisec ).toUtc();
}
print('${dateFromTimeUuid(uuid.v1(options: {
'node': [0x01, 0x23, 0x45, 0x67, …
```
> bad timestamp

- README.md
I suggest changing the title of the readme to the name of the actual Dart package to avoid (minor but unnecessary) confusion.
> Change title to name of package

- README.md
Not much to say
```diff
- Consturctor
+ Constructor
```
> Fix tiny typo in docs

- .travis.yml
- CHANGELOG.md
- lib/uuid.dart
- lib/uuid_util.dart
- pubspec.yaml
- test/uuid_test.dart
The migration was relatively straightforward:
- The library used to allocate byte buffers with `List<int>(16)`, which is not allowed in null-safe Dart. We now use an `Uint8List` with bytes initialized to `0` which is also more efficient
- I made `_byteToHex` a static field since its only needed once. This allows us to initialize it right away to avoid nullability issues
- I added three tests to verify that the `vXbuffer`-methods work as intended
- I replaced usages of `_hexToByte` with `int.parse`: This simplifies code, and parsing an int is probably cheaper than looking up strings.
The migration guide recommends increasing the major version after migrating to null safety, but I didn't have to make any breaking changes to the package so I think  `2.3.0` should be fine.
Closes #50, but it …
> Migrate to null safety

- pubspec.yaml
The first null-safe version of the `crypto` package has been released to pub, so we can replace the git dependency on crypto with a regular dependency.
We still need a dependency override because `test` doesn't support `crypto: ^3.0.0-nullsafety` yet, but since the conflicts only come from test (a `dev_dependency`), it should be safe to publish the null-safe version now!
> Remove git dependency override for crypto package

- lib/uuid.dart
- test/uuid_test.dart
Throw a `FormatException` when `Uuid.isValidUUID(uuid)` evaluates false when constructing a UuidValue instance.
> Uuidvalue input validation

- lib/uuid.dart
- pubspec.yaml
- test/uuid_test.dart
A microsoft guid i.e. 2400ee73-282c-4334-e153-08d8f922d1f9 wasn't matched by your isValidUUID regex pattern.
I think it makes sense, to be not stricter then really needed. Especially also I couldn't find the place in the RFC4122 where the first digit of the 'clock-seq-low' part of a uuid is limited, as it was by you regex pattern.  Probably there are many cases, where a rest api call and deserialization from json is made for uuid/guids from a Microsoft backend.
I hope that you're ok with this approach. Otherwise we also could implement a "strict" mode or v4guid or similar. But this makes the code unnecessarily complex.
> added support and test for microsoft guid

- lib/uuid.dart
Hello Daegalus,
Thank you so much for providing a great library, but I face a problem, that I got a uuid like this ('3d3e6f13-24c2-0ad6-3691-8d58fdb59b1c') and it couldn't pass the validation. I look back the code and find the validation that used before is not different. so I changed the pattern under non-Strict mode similar to before.
Thank you again!
> [Fix] Modify the pattern in nonStrict mode.

- lib/uuid.dart
- test/uuid_test.dart
Fixes #75 
I also added some tests to ensure it now behaves correctly. I found the following bugs, which are now fixed:
- global options are simply not used
- global v4 options used wrong keys for positional and named arguments
- global state was static, not a per instance member
- I decided to use an `Expando` for this, to keep backwards compability
- ~for this to be fixed I had to remove the `const` from the constructor. I am aware, that this is a potentially breaking change, but it is the "clean" way of doing this. If you prefer to do this without a breaking change, there is a way around that using the `Expando`. Just tell me which one you prefer.~
> Ensure constructor options are used correctly

- lib/uuid.dart
Noticed a type when reading the documentation for the v5 function and fixed it.
> v5 doc typo fix

- CHANGELOG.md
- lib/uuid.dart
- test/uuid_test.dart
Fixed `parse` method to allow _buffer_ and _offset_ parameters to be used as intended.
Previously, the code said `if (buffer.length != 16) throw ...` which means larger buffers cannot be passed in, and the only valid value for _offset_ is zero.
This code change allows for any buffer size as long as the number of bytes between the _offset_ and the end of the buffer is 16 bytes or greater.
> Fixed parse to allow buffers larger than 16 bytes to be used.

- lib/uuid_value.dart
This way developers can use `const` constructors where no values are immediately available.
Ex.
```
class Person {
final UuidValue id;
final String name;
final int age;
const Person({
required this.id,
required this.name,
required this.age,
});
static const empty = Person(
id: UuidValue.nil,
name: '',
age: 0,
);
}
```
I'm sure there are many other instances where this would be useful as well.
> Provide constants for RFC4122 namespaces in UuidValue

- lib/v6.dart
- lib/v7.dart
Fixes #89 
Flutter Web throws `Uint64List not supported by dart2js.` for UUIDv7 and `Uint64 accessor not supported by dart2js.` for UUIDv6 when trying to generate them, respectively.
This seems to be related to the following issues:
1. https://github.com/dart-lang/sdk/issues/10275
2. https://github.com/dart-lang/sdk/issues/50332
I found a workaround using `Uint32List` and adjusted the bits. Not sure if this is the optimal solution.
> Fix #89 v7: Uint64List not supported by dart2js. and v6: Uint64 accessor not supported by dart2js.

- lib/uuid.dart
- lib/uuid_value.dart
If you already have a UuidValue, `toBytes` should succeed if at all possible.
I ran into a case where I got a bluetooth service uuid that didn't validate for whatever reason, so when I went to serialize it back to disk it failed to serialize.  Turning off validation fixed it.
> toBytes no longer validates

- lib/rng.dart
Dart's `Random.secure` is _slow_. For example, every call to `nextInt()` opens a new handle to `/dev/urandom` on Android and Linux, and there is no API to get N random bytes.
A simple workaround here is to use `nextInt()` to request 4 bytes at a time instead of 1 (this is the maximum allowed). It's not great yet, but in my tests I can generate around twice as many V4 UUIDs per second with this change.
> Faster CryptoRNG

- CHANGELOG.md
- lib/uuid_value.dart
- pubspec.yaml
Adresses #98 
@daegalus Do you prefer to bump to 4.2.0 or 4.1.1? The 4.1.0 update wasn't really breaking, as the constructor wasn't made private nor it was marked as deprecated.
> Deprecation warning in default UuidValue constructor

- lib/rng.dart
Before this fix, it was generating the same Uint8List over and over if the initial seed was specified.
> fixed MathRNG - it now uses the initial seed properly

- lib/v5.dart
Fix for issue #111 where V5 was not working properly when using UTF-8 characters in the provided name.
> Fix V5 UUID inconsistencies when using UTF-8 characters

- README.md
- lib/data.dart
- lib/uuid.dart
- lib/v4.dart
Fixes https://github.com/daegalus/dart-uuid/issues/125
As mentioned [here](https://github.com/dart-lang/sdk/issues/56609#issuecomment-2321281919)
> Just want to add here that you should never generate UUID using default Random() generator. Use Random.secure() for that. Reason being that the amount of unique seeds for Random() are limited to 32 bits.
> So if you have lot of clients running, it is actually not that impossible to get two clients running with same seed just by accident.
The default RNG implementation should be `Random.secure()` not the plain `Random()`
> Always use `CryptoRNG` as the default

- lib/v8.dart
- lib/validation.dart
- pubspec.yaml
Going though dependencies, it looks like the `sprintf` dependency are not really justified based on the functionality being used of this package. I therefore suggest removing the package as dependency to reduce the amount of maintenance burden of dart-uuid.
I am not entirely sure why this hex converting logic are made like it is since it does not really generate "real" hex values since `2024` are converted to `0x2024` and not `0x07E8` which would be the correct value when converting `2024´ into hex.
To prevent failing tests and potential breaking changes, my implementation will still generate the exact same hex-like values as before the `sprintf` removal. But if we are open for changing this design, I can easily change the logic so we generate the needed `Uint8List` lists directly from …
> Remove `sprintf` dependency

- lib/uuid.dart
Update docs as `Uuid.NAMESPACE_URL` is deprecated.
> update docs for v5
